import base64

config = {
    "FILE_SERVER_PROTOCAL": 'http',
    "FILE_SERVER_HOST": "140.118.2.52",
    "FILE_SERVER_PORT": "34804",
    "FILE_SERVER_API_PREFIX": 'api',
    "FILE_SERVER_API_VERSION": 'v1.1.1',

    "ENTRY_SEVER_PROTCAL": 'http',
    "ENTRY_SEVER_HOST": '',
    "ENTRY_SEVER_PORT": '',
    "ENTRY_SEVER_API_PREFIX": '',
    "ENTRY_SEVER_API_VERSION": '',

    "DATASET_FILE_EXTENSION": "zip",
    "PIPELINE_FILE_EXTENSION": "py",
    "IMAGE_FILE_EXTENSION": "",
    "LOG_FILE_EXTENSION": "txt",
    "MODEL_FILE_EXTENSION": "zip"
}
