import base64

config = {
    "AUTHENTICATE_MIDDLEWARE_SERVER_PROTOCAL": 'http',
    "AUTHENTICATE_MIDDLEWARE_SERVER_HOST": "140.118.122.246",
    "AUTHENTICATE_MIDDLEWARE_SERVER_PORT": "50000",
    "AUTHENTICATE_MIDDLEWARE_SERVER_API_PREFIX": 'api',
    "AUTHENTICATE_MIDDLEWARE_SERVER_API_VERSION": 'v1.1.5',
    "AUTHENTICATE_MIDDLEWARE_MODULE_NEME": 'entrypoint',

    # "ENTRY_SEVER_PROTCAL": 'http',
    # "ENTRY_SEVER_HOST": '',
    # "ENTRY_SEVER_PORT": '',
    # "ENTRY_SEVER_API_PREFIX": '',
    # "ENTRY_SEVER_API_VERSION": '',

    "DATASET_FILE_EXTENSION": "zip",
    "PIPELINE_FILE_EXTENSION": "py",
    "IMAGE_FILE_EXTENSION": "",
    "LOG_FILE_EXTENSION": "txt",
    "MODEL_FILE_EXTENSION": "zip"
}
